---
name: Check lesson and build for all configs

on:
  pull_request:
  push:
    branches:
      - gh-pages

jobs:
  lint_common_files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: DavidAnson/markdownlint-cli2-action@v9
      - name: Install codespell
        run: |
          sudo apt-get install codespell
      - name: Check spelling
        run: |
          make spellcheck
      - name: Check episode Markdown syntax
        run: |
          markdownlint-cli2 _episodes
      - name: Check extra Markdown syntax
        run: |
          markdownlint-cli2 _extra

  check_lesson_and_build_default:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0.4'
          bundler-cache: true
      - uses: DavidAnson/markdownlint-cli2-action@v9
      - name: Install basic requirements
        run: |
          # Need this library for nokogiri
          sudo apt-get install libxslt1-dev
          gem install bundler json kramdown kramdown-parser-gfm
          bundle config set path '.vendor/bundle'
          bundle config build.nokogiri --use-system-libraries
          bundle install
      - name: "Lint episode markdown"
        run: |
          bundle exec mdl _episodes {} \;
      - name: "Check lesson for warnings"
        run: |
          make lesson-check-all
      - name: "Check lesson for errors"
        run: |
          make lesson-check
      - name: "Check build"
        run: |
          make --always-make site

  build-specific-sites:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        HPC_JEKYLL_CONFIG:
          - Birmingham_Baskerville_slurm
          - ComputeCanada_Graham_slurm
          - EPCC_Cirrus_pbs
          - HPCC_MagicCastle_slurm
          - Magic_Castle_EESSI_slurm
          - NIST_CTCMS_slurm
          - Norway_SIGMA2_SAGA_slurm
          - UCL_Myriad_sge
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0.4'
          bundler-cache: true
      - uses: DavidAnson/markdownlint-cli2-action@v9
      - name: Install basic requirements
        run: |
          # Need this library for nokogiri
          sudo apt-get install libxslt1-dev
          gem install bundler
          bundle config set path '.vendor/bundle'
          bundle config build.nokogiri --use-system-libraries
          bundle install
      - name: Check build ${{matrix.HPC_JEKYLL_CONFIG}}
        run: |
          make --always-make site HPC_JEKYLL_CONFIG=_includes/snippets_library/${{matrix.HPC_JEKYLL_CONFIG}}/_config_options.yml
      - name: Lint snippet markdown
        run: |
          markdownlint-cli2 "_includes/snippets_library/${{matrix.HPC_JEKYLL_CONFIG}}/**/*.snip"
